### PR TITLE
Use null for empty content, so it doesn't produce code

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by ktomk** [comment]
@GrahamCampbell Thanks for your PR. But I have no issue with writing the code, I also tried to explain it in the review.

And as it gets a little heated on such a detail, there is nothing with the PR to decide in the hours.

But I have already another suggestion and this time I filled an issue so that any conceptual issues can be clarified upfront and it's not that code-centric. It would be great if you could take a look with your sharp eyes: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4520

**Comment by GrahamCampbell** [comment]
Sure. :)

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by ktomk** [comment]
@GrahamCampbell Should we really hide this error? Shouldn't the person who applies this kind of fixer know about an error in the code?

**Comment by ktomk** [comment]
@GrahamCampbell I also have a problem finding the original PR. Was it this one? https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4518

**Comment by ktomk** [comment]
Let's just fix it. GIGO. But I think this needs a new PR upstream then.

**Comment by ktomk** [comment]
@GrahamCampbell Closing it here as stale and the original PR is merged since longer.

**Pull request closed without merging**
